//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_info
    {
        public int id { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string department { get; set; }
        public string year { get; set; }
        public int physics { get; set; }
        public int chemistry { get; set; }
        public int mathematics { get; set; }
        public string placement_status { get; set; }
        public string company { get; set; }
    
        public virtual userdetail userdetail { get; set; }
    }
}
